### ISSUE TITLE
Remove yarn.lock

### ISSUE THREAD

**Issue by davidnguyen11** [haoict/production-ready-webapp-boilerplate#2]
Remove yarn.lock & add `yarn.lock` to `.gitignore`

**Comment by haoict** [comment]
> As is covered elsewhere, dependency lock files, which are supported by many package management systems (e.g.: composer and bundler), should be committed to the codebase in end-of-chain projects - so that each individual trying to run that project is doing so with exactly the tested set of dependencies.

Source:
https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494
