### ISSUE TITLE
Warning: Potential Security Risk Ahead

### ISSUE THREAD

**Issue by Praexor** [haoict/production-ready-webapp-boilerplate#47]
Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to pokemon.nless.pro. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Comment by haoict** [comment]
Oh, I changed the domain. I should have updated README soon.
New domain:
Demo: https://pokemon.haoictdev.com
Demo Storybook: https://storybook.haoictdev.com
